visible = true
travel_to = rm_docks_south_warehouse_01
newX = 432
newY = 560
newDir = "up"
lock_level = 1 // Req: Lockpicking 1
locked = true
conditional = true
condition = quest_objective_is_visible(0, 8)