visible = true
travel_to = rm_docks_south_derelict_home
newX = 208
newY = 320
newDir = "up"
lock_level = 1 // Req: Lockpicking 1
locked = true
conditional = true
condition = quest_objective_is_visible(0, 8)